biostars:
    feed_url: 'http://www.biostars.org/feeds/latest/'
jira:
    username: 'johndoe'
    password: 'bestshow'
    base_url: 'https://jira.domain.com'
    project_key: 'FOO'
    issue_type_id: '42'
